### ISSUE TITLE
search_api bitte downgraden auf 1.7

### ISSUE THREAD

**Issue by gneher** [GFZ/open-semantic-framework#1]
Hallo Herr Seelus,

bitte search_api auf 1.7 downgraden, sonst funktionieren einige wichtige OSF-Module nicht korrekt.

Aktuelles search_api-Verzeichnis in "sites/all/modules/contrib" loeschen und durch http://ftp.drupal.org/files/projects/search_api-7.x-1.7.tar.gz ersetzen

Gruesse, G.Neher

**Comment by cseelus** [comment]
Hallo,

habe die aktuelle Version gesichert und durch die 1.7er ersetzt. Interessant wäre, ob das ein temporäres Problem ist oder ob man ab dem nächsten Release von `search_api` wieder die Drupal-Instanz aktuell halten kann. Gibt es dazu einen Thread auf der OSF Mailingliste, dem man folgen kann?

Grüße

**Comment by gneher** [comment]
Hallo,
danke!  - ich wuerde dann in den naechsten Tagen mal mit dem vm37-drupal experimentieren und versuchen, dass zu reproduzieren, was in meiner lokalen VM schonmal ganz viel versprechend aussieht. gibt es hierbei etwas zu beachten ?
P.S.
ob es einen osf-thread zu search_api gibt, weiss nicht. hatte nur in meiner VM gesehen, dass version <=1.7 verlangt wird. 

gruesse, g.neher
